<Project Sdk="Godot.NET.Sdk/4.5.1">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.Core" Version="4.0.3.9" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.17.2" />
    <PackageReference Include="XmppDotNet" Version="3.2.6" />
    <PackageReference Include="XmppDotNet.Transport.WebSocket" Version="3.2.6" />
  </ItemGroup>
</Project>